version: '3'

services:
  server:
    image: php:8-cli
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    command: php -S 0.0.0.0:4000 -t /app
  client:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
